version: "3"

services:
    apache:
        build: ./docker/apache
        ports:
            - "8081:80"
        environment:
            DOCKER_HOST: "unix:///var/run/docker.sock"
        volumes:
            - ./html:/var/www/html/:z
            - ./docker/apache/php.ini:/usr/local/etc/php/php.ini:z
        networks:
            - backend

    db:
        image: "mysql:8"
        volumes:
            - ./docker/db:/var/lib/mysql
        environment:
               MYSQL_ROOT_PASSWORD: pass
               MYSQL_DATABASE: sprava_lara
               MYSQL_USER: sprava_lara
               MYSQL_PASSWORD: pass
        networks:
            - backend

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            - PMA_HOST=db
            - PMA_USER=sprava_lara
            - PMA_PASSWORD=pass
        volumes:
            - ./docker/apache/upload.ini:/usr/local/etc/php/php.ini:z
            - /sessions
        ports:
            - "8082:80"
        networks:
            - backend

    rabbitmq:
        image: rabbitmq:3-management
        hostname: my-rabbit
        volumes:
            #- ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
            #- ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
            - ./docker/rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
            - ./docker/rabbitmq/logs:/var/log/rabbitmq/log
        ports:
            - 5672:5672
            - 15672:15672

    redis:
        image: redis:3.0
        ports:
            - "6379:6379"
        networks:
            - backend

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
        environment:
            - node.name=elastic
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es02,es03
            - cluster.initial_master_nodes=elastic
            - bootstrap.memory_lock=true
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./docker/elastic:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - backend

    kibana:
        image: kibana:7.7.0
        ports:
            - "5601:5601"
        networks:
            - backend
networks:
    backend: